# Generated by Django 5.2.2 on 2025-07-08 13:53

import django.db.models.deletion
import gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(height_field='image_height', upload_to=gui.models.annotated_image_upload_path, width_field='image_width')),
                ('image_height', models.IntegerField(blank=True, default=1)),
                ('image_width', models.IntegerField(blank=True, default=1)),
                ('class_color_map', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('class_counts', models.JSONField()),
                ('annotated_image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.annotatedimage')),
            ],
        ),
    ]
