# Generated by Django 5.2.2 on 2025-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedimage',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotatedimage',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
