name: Build Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: frontend/devision/dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --linux
      - uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: frontend/devision/dist/*.AppImage

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --mac
      - uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: frontend/devision/dist/*.dmg
