name: Build Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: frontend/devision/dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --linux
      - uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: frontend/devision/dist/*.AppImage

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: frontend/devision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --mac
      - uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: frontend/devision/dist/*.dmg

  publish-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: artifacts/

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-installer
          path: artifacts/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-installer
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            artifacts/*.exe
            artifacts/*.AppImage
            artifacts/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}